import turtle as trtl
painter=trtl
#head
painter.speed(0)
def talloval(r):
    painter.left(45)
    for loop in range(2):
        painter.circle(r,90)
        painter.circle(r/2,90)
painter.pensize(3)
painter.penup()
painter.goto(0,10)
painter.pendown()
painter.color("#FAEBD7")
painter.begin_fill()
talloval(100)
painter.end_fill()
painter.right(45)
painter.color("black")
talloval(100)
# mouth
painter.penup()
painter.goto(-35,50)
painter.pendown()
painter.right(45)
painter.forward(12)
painter.penup()
# eye 1
painter.goto(-40,100)
painter.pendown()
painter.color("white")
painter.begin_fill()
painter.forward(-28)
painter.right(90)
painter.circle(15,180)
painter.end_fill()
painter.right(90)
painter.color("black")
painter.penup()
painter.goto(-40,100)
painter.pendown()
painter.forward(-28)
painter.right(90)
painter.circle(15,180)
#eye 2
painter.penup()
painter.right(90)
painter.forward(20)
painter.pendown()
painter.forward(28)
painter.color("white")
painter.begin_fill()
painter.forward(-28)
painter.right(90)
painter.circle(15,180)
painter.end_fill()
painter.right(90)
painter.color("black")
painter.penup()
painter.goto(10,100)
painter.pendown()
painter.forward(-28)
painter.right(90)
painter.circle(15,180)
#eyebrow 1
painter.penup()
painter.right(90)
painter.goto(-60,100)
painter.forward(11)
painter.right(90)
painter.penup()
painter.goto(-70,100)
painter.left(180)
painter.forward(8)
painter.right(90)
painter.pendown()
painter.forward(35)
#eyebrow 2
painter.penup()
painter.goto(-20,100)
painter.left(90)
painter.forward(8)
painter.right(90)
painter.pendown()
painter.forward(35)
#pupil 1
painter.penup()
painter.goto(-50,95)
painter.pendown()
painter.dot()
#pupil 2
painter.penup()
painter.goto(0,95)
painter.pendown()
painter.dot()
painter.penup()
#lines
painter.goto(-86,130)
painter.pendown()
painter.forward(15)
painter.penup()
painter.goto(-84,135)
painter.pendown()
painter.forward(20)
painter.penup()
painter.goto(-82,140)
painter.pendown()
painter.forward(10)
painter.penup()
painter.goto(-77,145)
painter.pendown()
painter.forward(23)
painter.penup()
painter.goto(-73,150)
painter.pendown()
painter.forward(12)
painter.penup()
painter.goto(-68,155)
painter.pendown()
painter.forward(25)
painter.penup()
painter.goto(200,200)








wn = trtl.Screen()
wn.mainloop()

